### ISSUE TITLE
Color Palate?

### ISSUE THREAD

**Issue by rudyon** [nullxception/cherrita-gtk-theme#1]
Could you possibly make the color palate public? I would like to contribute into extending the theme into different applications.

**Comment by nullxception** [comment]
here's my base16 color that match with this theme (in alacritty config format) though if that's what you meant by color palletes : https://github.com/nullxception/dotfiles/blob/main/alacritty/colors/cherry.yml

**Comment by rudyon** [comment]
That is indeed what I meant by color palates thank you very much.
